import './Lexical.css'

export const wikiTheme = {
    paragraph: 'lexical-paragraph',
    quote: 'lexical-quote',
    heading: {
        h1: 'lexical-h1',
        h2: 'lexical-h2',
        h3: 'lexical-h3',
        h4: 'lexical-h4',
        h5: 'lexical-h5',
        h6: 'lexical-h6',
    },
    list: {
        listitem: 'lexical-listitem',
        listitemChecked: 'lexical-listitem-checked',
        listitemUnchecked: 'lexical-listitem-unchecked',
        nested: {
            listitem: 'lexical-nested-listitem',
        },
        ol: 'lexical-list-ol',
        ul: 'lexical-list-ul',
    },
    link: 'lexical-link',
    image: 'lexical-image',
    text: {
        bold: 'lexical-text-bold',
        code: 'lexical-text-code',
        italic: 'lexical-text-italic',
        strikethrough: 'lexical-text-strikethrough',
        underline: 'lexical-text-underline',
        underlineStrikethrough: 'lexical-text-underline-strikethrough',
    },
    code: 'lexical-code',
    codeHighlight: {
        atrule: 'lexical-token-attr',
        attr: 'lexical-token-attr',
        boolean: 'lexical-token-property',
        builtin: 'lexical-token-selector',
        cdata: 'lexical-token-comment',
        char: 'lexical-token-selector',
        class: 'lexical-token-function',
        'class-name': 'lexical-token-function',
        comment: 'lexical-token-comment',
        constant: 'lexical-token-property',
        deleted: 'lexical-token-property',
        doctype: 'lexical-token-comment',
        entity: 'lexical-token-operator',
        function: 'lexical-token-function',
        important: 'lexical-token-variable',
        inserted: 'lexical-token-selector',
        keyword: 'lexical-token-attr',
        namespace: 'lexical-token-variable',
        number: 'lexical-token-property',
        operator: 'lexical-token-operator',
        prolog: 'lexical-token-comment',
        property: 'lexical-token-property',
        punctuation: 'lexical-token-punctuation',
        regex: 'lexical-token-variable',
        selector: 'lexical-token-selector',
        string: 'lexical-token-selector',
        symbol: 'lexical-token-property',
        tag: 'lexical-token-property',
        url: 'lexical-token-operator',
        variable: 'lexical-token-variable',
    },
    table: 'lexical-table',
    tableCell: 'lexical-table-cell',
    tableCellHeader: 'lexical-table-cell-header',
    tableRow: 'lexical-table-row',
    layoutContainer: 'lexical-layout-container',
    layoutItem: 'lexical-layout-item',
}
