/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsOfServiceRouteImport } from './routes/_public/terms-of-service'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as AppDashboardRouteImport } from './routes/_app/_dashboard'
import { Route as AppPageIdRouteImport } from './routes/_app/page.$id'
import { Route as AppDashboardStarredRouteImport } from './routes/_app/_dashboard/starred'
import { Route as AppDashboardSharedWithMeRouteImport } from './routes/_app/_dashboard/shared-with-me'
import { Route as AppDashboardSearchRouteImport } from './routes/_app/_dashboard/search'
import { Route as AppDashboardNewRouteImport } from './routes/_app/_dashboard/new'
import { Route as AppDashboardHomeRouteImport } from './routes/_app/_dashboard/home'
import { Route as AppDashboardArchiveRouteImport } from './routes/_app/_dashboard/archive'

const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsOfServiceRoute = PublicTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPageIdRoute = AppPageIdRouteImport.update({
  id: '/page/$id',
  path: '/page/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardStarredRoute = AppDashboardStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSharedWithMeRoute =
  AppDashboardSharedWithMeRouteImport.update({
    id: '/shared-with-me',
    path: '/shared-with-me',
    getParentRoute: () => AppDashboardRoute,
  } as any)
const AppDashboardSearchRoute = AppDashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardNewRoute = AppDashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardHomeRoute = AppDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardArchiveRoute = AppDashboardArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/drive': typeof DriveRoute
  '/faq': typeof PublicFaqRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/archive': typeof AppDashboardArchiveRoute
  '/home': typeof AppDashboardHomeRoute
  '/new': typeof AppDashboardNewRoute
  '/search': typeof AppDashboardSearchRoute
  '/shared-with-me': typeof AppDashboardSharedWithMeRoute
  '/starred': typeof AppDashboardStarredRoute
  '/page/$id': typeof AppPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/drive': typeof DriveRoute
  '/faq': typeof PublicFaqRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/archive': typeof AppDashboardArchiveRoute
  '/home': typeof AppDashboardHomeRoute
  '/new': typeof AppDashboardNewRoute
  '/search': typeof AppDashboardSearchRoute
  '/shared-with-me': typeof AppDashboardSharedWithMeRoute
  '/starred': typeof AppDashboardStarredRoute
  '/page/$id': typeof AppPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/drive': typeof DriveRoute
  '/_app/_dashboard': typeof AppDashboardRouteWithChildren
  '/_public/faq': typeof PublicFaqRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/terms-of-service': typeof PublicTermsOfServiceRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/_dashboard/archive': typeof AppDashboardArchiveRoute
  '/_app/_dashboard/home': typeof AppDashboardHomeRoute
  '/_app/_dashboard/new': typeof AppDashboardNewRoute
  '/_app/_dashboard/search': typeof AppDashboardSearchRoute
  '/_app/_dashboard/shared-with-me': typeof AppDashboardSharedWithMeRoute
  '/_app/_dashboard/starred': typeof AppDashboardStarredRoute
  '/_app/page/$id': typeof AppPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drive'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/archive'
    | '/home'
    | '/new'
    | '/search'
    | '/shared-with-me'
    | '/starred'
    | '/page/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drive'
    | '/faq'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/archive'
    | '/home'
    | '/new'
    | '/search'
    | '/shared-with-me'
    | '/starred'
    | '/page/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/drive'
    | '/_app/_dashboard'
    | '/_public/faq'
    | '/_public/privacy-policy'
    | '/_public/terms-of-service'
    | '/_public/'
    | '/_app/_dashboard/archive'
    | '/_app/_dashboard/home'
    | '/_app/_dashboard/new'
    | '/_app/_dashboard/search'
    | '/_app/_dashboard/shared-with-me'
    | '/_app/_dashboard/starred'
    | '/_app/page/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DriveRoute: typeof DriveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms-of-service': {
      id: '/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PublicTermsOfServiceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/_dashboard': {
      id: '/_app/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/page/$id': {
      id: '/_app/page/$id'
      path: '/page/$id'
      fullPath: '/page/$id'
      preLoaderRoute: typeof AppPageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_dashboard/starred': {
      id: '/_app/_dashboard/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof AppDashboardStarredRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/shared-with-me': {
      id: '/_app/_dashboard/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof AppDashboardSharedWithMeRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/search': {
      id: '/_app/_dashboard/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppDashboardSearchRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/new': {
      id: '/_app/_dashboard/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppDashboardNewRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/home': {
      id: '/_app/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppDashboardHomeRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/_dashboard/archive': {
      id: '/_app/_dashboard/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppDashboardArchiveRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardArchiveRoute: typeof AppDashboardArchiveRoute
  AppDashboardHomeRoute: typeof AppDashboardHomeRoute
  AppDashboardNewRoute: typeof AppDashboardNewRoute
  AppDashboardSearchRoute: typeof AppDashboardSearchRoute
  AppDashboardSharedWithMeRoute: typeof AppDashboardSharedWithMeRoute
  AppDashboardStarredRoute: typeof AppDashboardStarredRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardArchiveRoute: AppDashboardArchiveRoute,
  AppDashboardHomeRoute: AppDashboardHomeRoute,
  AppDashboardNewRoute: AppDashboardNewRoute,
  AppDashboardSearchRoute: AppDashboardSearchRoute,
  AppDashboardSharedWithMeRoute: AppDashboardSharedWithMeRoute,
  AppDashboardStarredRoute: AppDashboardStarredRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppPageIdRoute: typeof AppPageIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppPageIdRoute: AppPageIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTermsOfServiceRoute: typeof PublicTermsOfServiceRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFaqRoute: PublicFaqRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTermsOfServiceRoute: PublicTermsOfServiceRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DriveRoute: DriveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
