/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikisRouteImport } from './routes/wikis'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SharedWithMeRouteImport } from './routes/shared-with-me'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewRouteImport } from './routes/new'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageIdRouteImport } from './routes/page.$id'

const WikisRoute = WikisRouteImport.update({
  id: '/wikis',
  path: '/wikis',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedWithMeRoute = SharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/page/$id',
  path: '/page/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/drive': typeof DriveRoute
  '/faq': typeof FaqRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/starred': typeof StarredRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wikis': typeof WikisRoute
  '/page/$id': typeof PageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/drive': typeof DriveRoute
  '/faq': typeof FaqRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/starred': typeof StarredRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wikis': typeof WikisRoute
  '/page/$id': typeof PageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/drive': typeof DriveRoute
  '/faq': typeof FaqRoute
  '/new': typeof NewRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/starred': typeof StarredRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wikis': typeof WikisRoute
  '/page/$id': typeof PageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/drive'
    | '/faq'
    | '/new'
    | '/privacy-policy'
    | '/shared-with-me'
    | '/starred'
    | '/terms-of-service'
    | '/wikis'
    | '/page/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/drive'
    | '/faq'
    | '/new'
    | '/privacy-policy'
    | '/shared-with-me'
    | '/starred'
    | '/terms-of-service'
    | '/wikis'
    | '/page/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/drive'
    | '/faq'
    | '/new'
    | '/privacy-policy'
    | '/shared-with-me'
    | '/starred'
    | '/terms-of-service'
    | '/wikis'
    | '/page/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  DriveRoute: typeof DriveRoute
  FaqRoute: typeof FaqRoute
  NewRoute: typeof NewRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SharedWithMeRoute: typeof SharedWithMeRoute
  StarredRoute: typeof StarredRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WikisRoute: typeof WikisRoute
  PageIdRoute: typeof PageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wikis': {
      id: '/wikis'
      path: '/wikis'
      fullPath: '/wikis'
      preLoaderRoute: typeof WikisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-with-me': {
      id: '/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof SharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$id': {
      id: '/page/$id'
      path: '/page/$id'
      fullPath: '/page/$id'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  DriveRoute: DriveRoute,
  FaqRoute: FaqRoute,
  NewRoute: NewRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SharedWithMeRoute: SharedWithMeRoute,
  StarredRoute: StarredRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WikisRoute: WikisRoute,
  PageIdRoute: PageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
